### ISSUE TITLE
Make IntegrityJenkinsPlugin usable within Pipeline jobs

### ISSUE THREAD

**Issue by vlad2011** [integrity-tf/jenkins#19]
The following links might be helpful by the implementation:
https://jenkins.io/blog/2016/05/25/update-plugin-for-pipeline/
https://jenkins.io/doc/developer/plugin-development/pipeline-integration/

The issue is somehow related to https://github.com/integrity-tf/integrity/issues/157.

**Comment by S1artie** [comment]
Implemented and positively tested on a production Jenkins installation.
