### ISSUE TITLE
status and color at integrity result overview

### ISSUE THREAD

**Issue by canderwald** [integrity-tf/jenkins#22]
Please improve the integrity result overview. It would be helpful if the result lines have got different background colors for the status, e.g. green for 0 failures and 0 errors, yellow for failures > 0 and red for errors > 0. Maybe an addtional column that contains the status success, failure, error can be added, too.

**Comment by S1artie** [comment]
![bildschirmfoto 2019-02-22 um 15 32 22](https://user-images.githubusercontent.com/3661818/53248932-1920b600-36b7-11e9-9097-c04ab1069e13.png)
